### ISSUE TITLE
miniflare does not work with realm-web

### ISSUE THREAD

**Issue by syffs** [cloudflare/miniflare#136]
I'm getting the below exception when using realm-web on miniflare:
```sh
 Error: DefaultNetworkTransport.AbortController must be set before it's used
    at new Er (/project/node_modules/realm-web/dist/bundle.dom.es.js:230:19)
    at new Ar (/project/node_modules/realm-web/dist/bundle.dom.es.js:3171:38)
    at qd (/project/src/index.ts:156:18)
    at Object.handler (/project/src/index.ts:241:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at run (/project/node_modules/worktop/router/index.mjs:69:34)
    at fetch (/project/node_modules/worktop/cache/index.mjs:22:40)
    at EventTarget.[dispatchFetch] (/project/node_modules/miniflare/src/modules/events.ts:207:25)
    at Miniflare._Miniflare_httpRequestListener (/project/node_modules/miniflare/src/index.ts:416:20)
```

in my project: `    at qd (/project/src/index.ts:156:18)` is:
```js
App = App || new Realm.App(appId)
```
Here is [repro](https://github.com/syffs/cloudflare-worker-rest-api-realm-atlas/tree/miniflare)

also posted mongodb-developer/cloudflare-worker-rest-api-realm-atlas#5

**Comment by syffs** [comment]
Took me a while, but I figured out that miniflare v1 does not handle [latest workers runtime](https://community.cloudflare.com/t/2021-9-24-workers-runtime-release-notes/308821) with. 

Upgrading miniflare to v2 fixes this.
