### ISSUE TITLE
Maximum call stack size exceeded getting time

### ISSUE THREAD

**Issue by WalshyDev** [cloudflare/miniflare#314]
Hey, got hit by "Maximum call stack size exceeded" today with `wrangler pages dev` and visiting the page:
```
[pages:err] RangeError: Maximum call stack size exceeded
    at Object.getRequestContext (/site/node_modules/@miniflare/shared/src/index.ts:1:1)
    at Object.get [as getRequestContext] (/site/node_modules/@miniflare/core/dist/src/index.js:18:52)
    at Function.requestContextNow (/site/node_modules/@miniflare/core/src/standards/date.ts:5:10)
    at Function.requestContextNow (/site/node_modules/@miniflare/core/src/standards/date.ts:5:51)
    at Function.requestContextNow (/site/node_modules/@miniflare/core/src/standards/date.ts:5:51)
    at Function.requestContextNow (/site/node_modules/@miniflare/core/src/standards/date.ts:5:51)
    at Function.requestContextNow (/site/node_modules/@miniflare/core/src/standards/date.ts:5:51)
    at Function.requestContextNow (/site/node_modules/@miniflare/core/src/standards/date.ts:5:51)
    at Function.requestContextNow (/site/node_modules/@miniflare/core/src/standards/date.ts:5:51)
    at Function.requestContextNow (/site/node_modules/@miniflare/core/src/standards/date.ts:5:51)
```

MRE:
```js
Date.now = Date.now || function() {
  return +new Date();
};

export default {
  fetch() {
    return new Response('Hello, World');
  }
}
```

The Date.now part was taken from `bcryptjs` which I found out was the culprit!

```
$ miniflare --version
2.6.0

$ miniflare --modules worker.js
[mf:inf] Worker reloaded! (137B)
[mf:inf] Listening on :8787
[mf:inf] - http://127.0.0.1:8787
[mf:inf] - http://192.168.0.5:8787
[mf:inf] Updated `Request.cf` object cache!
[mf:err] GET /: RangeError: Maximum call stack size exceeded
    at Object.getRequestContext (/home/walshy/.nvm/versions/node/v16.13.0/lib/node_modules/miniflare/node_modules/@miniflare/shared/src/index.ts:1:1)
    at Object.get [as getRequestContext] (/home/walshy/.nvm/versions/node/v16.13.0/lib/node_modules/miniflare/node_modules/@miniflare/core/dist/src/index.js:18:52)
    at Function.requestContextNow (/home/walshy/.nvm/versions/node/v16.13.0/lib/node_modules/miniflare/node_modules/@miniflare/core/src/standards/date.ts:5:10)
    at Function.requestContextNow (/home/walshy/.nvm/versions/node/v16.13.0/lib/node_modules/miniflare/node_modules/@miniflare/core/src/standards/date.ts:5:51)
    at Function.requestContextNow (/home/walshy/.nvm/versions/node/v16.13.0/lib/node_modules/miniflare/node_modules/@miniflare/core/src/standards/date.ts:5:51)
    at Function.requestContextNow (/home/walshy/.nvm/versions/node/v16.13.0/lib/node_modules/miniflare/node_modules/@miniflare/core/src/standards/date.ts:5:51)
    at Function.requestContextNow (/home/walshy/.nvm/versions/node/v16.13.0/lib/node_modules/miniflare/node_modules/@miniflare/core/src/standards/date.ts:5:51)
    at Function.requestContextNow (/home/walshy/.nvm/versions/node/v16.13.0/lib/node_modules/miniflare/node_modules/@miniflare/core/src/standards/date.ts:5:51)
    at Function.requestContextNow (/home/walshy/.nvm/versions/node/v16.13.0/lib/node_modules/miniflare/node_modules/@miniflare/core/src/standards/date.ts:5:51)
    at Function.requestContextNow (/home/walshy/.nvm/versions/node/v16.13.0/lib/node_modules/miniflare/node_modules/@miniflare/core/src/standards/date.ts:5:51)
GET / 500 Internal Server Error (90.80ms)

```

Wrangler dev and prod work fine:
```
wrangler dev worker.js 
 ⛅️ wrangler 2.0.21 
--------------------
Retrieving cached values for userId from node_modules/.cache/wrangler
⬣ Listening at http://localhost:8787
Total Upload: 0.23 KiB / gzip: 0.17 KiB
Script modified; context reset.
17:08:52 GET / 200
17:08:52 GET /favicon.ico 200
```

---

Unsurprisingly, this works fine with `--actual-time`
```
miniflare --modules --actual-time worker.js
[mf:inf] Worker reloaded! (138B)
[mf:inf] Listening on :8787
[mf:inf] - http://127.0.0.1:8787
[mf:inf] - http://192.168.0.5:8787
GET / 200 OK (9.68ms)
GET /favicon.ico 200 OK (1.50ms)
```

**Comment by WalshyDev** [comment]
MRE:
```
Date.now = Date.now || function() {
  return +new Date();
};

export default {
  fetch() {
    return new Response('Hello, World');
  }
}
```

The Date.now part was taken from `bcryptjs` which I found out was the culprit! (Sorry for blaming you Remix :heart:)

**Comment by tokenhousetopdev** [comment]
I encountered this issue as well.

**Comment by AggressivelyMeows** [comment]
While trying to get the same API deployed locally, I ran into an issue where the `--actual-time` flag isnt being passed to the mounted service. Adding a console.log to date.ts:

**The main API**
![](https://nyc3.digitaloceanspaces.com/cerulean/screenshots/2022/08/Code_S92QQUGlP2.png)

**The mounted service**
![](https://nyc3.digitaloceanspaces.com/cerulean/screenshots/2022/08/Code_6mke4pJ8ya.png)
