### ISSUE TITLE
"require is not defined" when initializing DB with d1 beta bindings

### ISSUE THREAD

**Issue by tgriesser** [cloudflare/miniflare#400]
Was trying out the d1 beta bindings in miniflare, and ran into the following:

```
[mf:err] ReferenceError: require is not defined
    at _resolve (file:///Users/tgriesser/Github/cf-test/node_modules/.pnpm/npx-import@1.1.3/node_modules/npx-import/lib/utils.js:11:5)
    at npxResolve (file:///Users/tgriesser/Github/cf-test/node_modules/.pnpm/npx-import@1.1.3/node_modules/npx-import/lib/index.js:56:16)
    at createSQLiteDB (/Users/tgriesser/Github/cf-test/node_modules/.pnpm/@miniflare+shared@2.9.0/node_modules/@miniflare/shared/src/sqlite.ts:20:51)
    at FileStorage.getSqliteDatabase (/Users/tgriesser/Github/cf-test/node_modules/.pnpm/@miniflare+storage-file@2.9.0/node_modules/@miniflare/storage-file/src/index.ts:114:21)
```

Seems it's due to this code in [`npx-import`](https://github.com/geelen/npx-import), which is a package of `"type": "module"`:

```ts
export function _resolve(packageWithPath: string) {
  return require.resolve(packageWithPath)
}
```

I believe this needs to be changed to create require:

```ts
export function _resolve(packageWithPath: string) {
  return createRequire(import.meta.url).resolve(packageWithPath)
}
```

Tried to patch and write a test for it in the `npx-import` package, but couldn't figure out getting vitest to load the test in a way that it'd fail, where `require` is undefined. Didn't see a way to force load as a true esm environment, seems `require` is [always defined](https://github.com/vitest-dev/vitest/blob/f55fa26063d80867897d5227f06f929a44a584a5/packages/vite-node/src/client.ts#L309-L311) in the worker context.

The other fix that seemed to work was to change:

https://github.com/cloudflare/miniflare/blob/974c7c2796cfa243f8eb0569cd2f37b59795ed71/packages/shared/src/sqlite.ts#L19-L21

to just use `require.resolve` directly:

```ts
return new DatabaseConstructor(dbPath, {
  nativeBinding: getSQLiteNativeBindingLocation(require.resolve("better-sqlite3")),
});
```

Figured @geelen would know better where is best to fix this, or if there was something else I was missing here where the current code is expected.

**Comment by CraigglesO** [comment]
My understanding is this PR fixes it:
https://github.com/geelen/npx-import/pull/9

**Comment by geelen** [comment]
Released `npx-import@v1.1.4`. Does miniflare/wrangler need to be published to pick this up or nah? Probably wrangler cause it bundles its dependencies, hey...

**Comment by penalosa** [comment]
@mrbbot I guess this needs a Miniflare release, and then a Wrangler release?

**Comment by BeeeQueue** [comment]
You can add a `resolution` to your `package.json` to fix it in the meantime.

```json
  "resolutions": {
    "npx-import": "1.1.4"
  }
```

**Comment by Skye-31** [comment]
This should be shipped on any fresh installation of Miniflare/Wrangler - this issue can be closed 🙂

**Comment by BeeeQueue** [comment]
I just installed/updated them when I wrote that comment and had to add the resolution. 😕
