### ISSUE TITLE
Miniflare does not support dynamic imports in module mode

### ISSUE THREAD

**Issue by calebmer** [cloudflare/miniflare#456]
Dynamic `import()`s do not work in Miniflare but appear to work when deploying to Cloudflare Workers in production. Below is a reproduction modifying the example from this [blog post](https://blog.cloudflare.com/workers-javascript-modules/). I am using dynamic imports to speed up worker startup time.

```ts
// filename: ./src/error.js
export async function logError(url, error) {
  await fetch(url, {
     method: "POST",
     body: error.stack
  })
}
```

```ts
// filename: ./src/worker.js
export default {
  async fetch(request, environment, context) {
    const {logError} = await import('./src/error.js');
    try {
       return await fetch(request);
    } catch (error) {
       context.waitUntil(logError(environment.ERROR_URL, error));
       return new Response("Oops!", { status: 500 });
    }
  }
}
```

You get the error:

```
TypeError: A dynamic import callback was not specified.
    at new NodeError (node:internal/errors:393:5)
    at importModuleDynamicallyCallback (node:internal/process/esm_loader:39:9)
    at getEmailPreviews (/server/emails/get_email_previews.ts:10:29)
    at loader (/app/routes/sign-in/index.tsx:30:11)
    at callRouteLoader (/node_modules/@remix-run/server-runtime/dist/esm/server.js:279:108
    at Array.map (<anonymous>)
    at handleDocumentRequest (/node_modules/@remix-run/server-runtime/dist/esm/server.js:279:67)
    at handleRequest (/node_modules/@remix-run/server-runtime/dist/esm/server.js:68:24)
    at /node_modules/@remix-run/cloudflare-workers/dist/esm/worker.js:35:12
```

Module rules is being set to `modulesRules: [{type: "ESModule", include: ["**/*.js"], fallthrough: true}]` .

This error is thrown when `importModuleDynamically` is not set on `SourceTextModule`.

https://github.com/cloudflare/miniflare/blob/6efbf41c4515b06ea50ec5fa89847d506908548d/packages/runner-vm/src/index.ts#L33-L36

Here’s an example of Jest’s implementation of the function:

https://github.com/facebook/jest/blob/41bf2300895a2c00d0525d21260f0a392819871f/packages/jest-runtime/src/index.ts#L625-L648

**Comment by calebmer** [comment]
The following patch on `@miniflare/runner-vm` with [`patch-package`](https://npmjs.org/patch-package) works for me:

```patch
diff --git a/dist/src/index.js b/dist/src/index.js
index fb79bb02047bb0b978286ab645cc5298da8e6341..47d061c1ff435f98d1ee1b72a2625e1d1c61cef1 100644
--- a/dist/src/index.js
+++ b/dist/src/index.js
@@ -151,7 +151,22 @@ ${suggestion}`);
     this.#referencedPathSizes.set(identifier, data.byteLength);
     switch (rule.type) {
       case "ESModule":
-        module2 = new import_vm2.default.SourceTextModule(data.toString("utf8"), moduleOptions);
+        module2 = new import_vm2.default.SourceTextModule(data.toString("utf8"), {
+          ...moduleOptions,
+          // NOTE(calebmer): Use the linker to support dynamic `import()`
+          // expressions.
+          importModuleDynamically: async (spec, referencing) => {
+            const module = await this.linker(spec, referencing);
+            // Defend against concurrent execution by only calling `link()` and
+            // `evaluate()` once and stashing the resulting promise so concurrent
+            // executions can await it.
+            if (module.status === "unlinked") module._linkPromise = module.link(this.linker);
+            await module._linkPromise;
+            if (module.status === "linked") module._evaluatePromise = module.evaluate();
+            await module._evaluatePromise;
+            return module;
+          },
+        });
         break;
       case "CommonJS":
         const exports = this.loadCommonJSModule(errorBase, identifier, spec, referencing.context);
@@ -256,7 +271,20 @@ var VMScriptRunner = class {
   async runAsModule(context, blueprint, linker) {
     const module2 = new import_vm3.default.SourceTextModule(blueprint.code, {
       identifier: blueprint.filePath,
-      context
+      context,
+      // NOTE(calebmer): Use the linker to support dynamic `import()`
+      // expressions.
+      importModuleDynamically: async (spec, referencing) => {
+        const module = await linker(spec, referencing);
+        // Defend against concurrent execution by only calling `link()` and
+        // `evaluate()` once and stashing the resulting promise so concurrent
+        // executions can await it.
+        if (module.status === "unlinked") module._linkPromise = module.link(linker);
+        await module._linkPromise;
+        if (module.status === "linked") module._evaluatePromise = module.evaluate();
+        await module._evaluatePromise;
+        return module;
+      },
     });
     await module2.link(linker);
     await module2.evaluate();
```
